name: SFDX-CLI Deploy from Repository
# Definition of when the workflow should run
on:
    workflow_dispatch:
jobs:
  SFDX-CLI-Deploy:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🐧 GitHub Action running on ${{ runner.os }}"
      - run: echo "🔎 Retrieving ${{ github.ref }} from ${{ github.repository }}."
      - uses: actions/checkout@v2
      - run: cd sample-sfdx-repo-workflow && npm install sfdx-cli -g
      - run: echo "${{ secrets.SALESFORCE_JWT_SECRET_KEY }}" > server.key
      - run: cd sample-sfdx-repo-workflow && sf org login jwt --client-id ${{ secrets.SALESFORCE_CONSUMER_KEY }} --jwt-key-file server.key --username ${{ secrets.SALESFORCE_DEVHUB_USERNAME }} --set-default-dev-hub
      - run: cd sample-sfdx-repo-workflow && sfdx force:source:deploy -p force-app/main/default --testlevel=RunLocalTests -u ${{ secrets.SALESFORCE_DEVHUB_USERNAME }}
